### ISSUE TITLE
Getting buffs from food in multiplayer apply to all players

### ISSUE THREAD

**Issue by Leafy-Greens** [Kevun1/Spice-of-Life-Potato-Edition#11]
I play on a small server with friends, and whenever someone consumes enough food to get benefits from it, everyone will get the buffs. As far as we're aware this is not an intended feature; we couldn't find any configs relating to it, and there's been no other bug reports relating to this issue either.

**Comment by Kevun1** [comment]
whoops, fixed with 1.1.0
