### ISSUE TITLE
[First Aid Compatibility] Health Depletion on eating foods

### ISSUE THREAD

**Issue by NotoriusQ** [Kevun1/Spice-of-Life-Potato-Edition#4]
So I thought it was happening only when I broke a new threshold, but I guess it's actually any time I eat food if I'm above the first threshold.
It goes, I eat, I take damage, all the debuffs for area damage are applied, and my first aid health gui shows all hearts empty, but then I stay alive until the next dmg instance.

Other mods that are modifying my health system -

First Aid - https://www.curseforge.com/minecraft/mc-mods/first-aid
LevelHearts - https://www.curseforge.com/minecraft/mc-mods/levelhearts
Simple Absorption - https://www.curseforge.com/minecraft/mc-mods/simple-absorption
Stats Keeper - https://www.curseforge.com/minecraft/mc-mods/simple-absorption

If there's any other information I can provide to help, please let me know!

**Comment by Kevun1** [comment]
This should be fixed with version 1.0.4. 

One minor inconvenience I've noticed still is that first aid plays the damaged sound/animation when max health increases, even if you don't lose any health, but that's not something I can change on my end.
