### ISSUE TITLE
Crashing on Config Edits [Simple Absorb +  Survive Compatibility]

### ISSUE THREAD

**Issue by NotoriusQ** [Kevun1/Spice-of-Life-Potato-Edition#5]
After adding attributes to the config with just these three mods installed, the world crashes while trying to load in.

[crash-2021-01-04_09.55.25-server.txt](https://github.com/Kevun1/Spice-of-Life-Potato-Edition/files/5765327/crash-2021-01-04_09.55.25-server.txt)

**To Reproduce**
Changed base absorptoin to 20 in config and added ";attribute,simple_absorption:absorption_max,4" to the first three thresholds (which worked without survive)
Reload into world and it closes down.

**Mod version and Forge version**
Forge Latest ~ .29
Survive 3.0.7
Simple Absorption 1.2.0
SoL:Potato 1.0.6

**Comment by Kevun1** [comment]
Double check to make sure you are on solpotato 1.0.6. Just in case I accidentally forgot to upload the correct version to curseforge, I've uploaded a version 1.0.7 which should definitely prevent any crashes.

That being said, the attribute modifier from solpotato still doesn't work with Survive installed -- it just doesn't crash anymore. In your log, you should see `ERROR: player does not have attribute: simple_absorption:absorption_max`, meaning for some reason, `player.getAttribute()` is returning null for `simple_absorption:absorption_max`. So the attribute modifier will not work.

This *only* happens with Survive installed (it works fine with just solpotato + simple absorption), so for some reason, survive is doing something wonky with attributes. This mod doesn't touch adding/removing attributes at all (only attribute modifiers), so I don't think its a problem on my end. I can report  this to the survive issue.
